project:
  type: website

website:
  title: "mariamaladsani.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Assignments
        menu:
          - assign01.qmd
          - assign02.qmd
          - assign03.qmd
          - assign06.qmd
          - assign07.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

