---
title: "About"
---

I am currently a master's student at the University of Texas at Dallas' Applied Cognition and Neuroscience program. In the spring of 2022, I graduated from Boston University with a BA in Psychology and a double minor in Philosophy and Comparative Literature. During my undergraduate career, I partook in research involving molecular neuroscience and clinical neuropsychology. In Dr. Ryan Logan's lab in the Boston University School of Medicine, I worked on a project that investigated the role of circadian rhythms in opiod-seeking, craving, and relapse. At the Manoach Lab at Massachusetts General Hospital, I worked on a study investigating the relationship between memory consolidation and sleep in schizophrenic patients using EEG, MRI, and MEG, as well as neuropsychological assessments.

During my graduate studies I am hoping to bridge my interests in both molecular neuroscience and neuropsychology. I am interested in how social and environmental factors in early life can impact and/or impair cognitive functions like memory later on in life. Overall, I aspire to be a well-rounded neuroscientist by conducting research that draws from different disciplines and methods.

You can find my CV [here](https://docs.google.com/document/d/16osp8t1dSTJ0PPVI4Z3f3Ius9BsZkYb7/edit?usp=sharing&ouid=112248111695570791626&rtpof=true&sd=true).

```{r}
1 + 1
```
