---
title: "assign02"
---

## Assignment 2: gTrends

I examined that number of searches for 'Trump' following the announcement of his election on June 6th 2015 for the 2016 US Election, up until 2023. I also examined the searches for 'Biden' following the same dates as my previous search.

In October and November 2016 there was a spike in searches for 'Trump,' coinciding to the election date. There was another sharp peak in 'Trump,' searches in October and November 2020. The search item 'Biden' was at its peak between the years of 2015 and 2023 in November 2020 during the election. Following the November 2020 election there was still more searches for 'Biden,' compared years 2015-early 2019, but not as frequent as the years of 2019 and 2020. The term 'Election' has a varied number of searches over time. The highest peaks being November 2016 and November 2020. There was a sharp dip of searches after January 2021, with some peaks in the searches in early to mid 2023.

All of the searches were exclusive to Google trends in the United States.
